spring.application.name=mac-backend
spring.config.import=optional:file:.env[.properties]

# Path default
server.servlet.context-path=/mac-api

# Servidor
server.port=${PORT:8080}

app.jwt.secret=${JWT_SECRET}
#app.jwt.access-token-expiration=900000
app.jwt.access-token-expiration=60000
app.jwt.refresh-token-expiration=604800000

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework.security=DEBUG

https.secure=${HTTPS_SECURE:true}
https.same-site=${SAME_SITE}

app.cors.allowed-origins=${ALLOWED_ORIGINS}