spring.application.name=mac-backend
spring.config.import=optional:file:.env[.properties]

# Path default
server.servlet.context-path=/mac-api

# Servidor
server.port=${PORT:8080}

app.jwt.secret=${JWT_SECRET}
app.jwt.access-token-expiration=1800000
app.jwt.refresh-token-expiration=604800000

app.cors.allowed-origins=${ALLOWED_ORIGINS}

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Pool
# Tamanho do pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=4

# Detecta conexoes que ficaram abertas por mais de 60s (leak detection)
spring.datasource.hikari.leak-detection-threshold=60000

# Tempo maximo esperando uma conexao livre do pool (5s)
spring.datasource.hikari.connection-timeout=5000

# Tempo maximo que uma conexao fica idle antes de ser descartada (10min)
spring.datasource.hikari.idle-timeout=600000

# Tempo maximo de vida de uma conexao (30min)
spring.datasource.hikari.max-lifetime=1800000

https.secure=${HTTPS_SECURE:true}
https.same-site=${SAME_SITE}
https.domain=${DOMAIN}

logging.level.org.springframework.security=DEBUG